- name: Géonature
  hosts: all
  tasks:
    - name: Install backend packages
      become: true
      apt:
        pkg:
        - python3
        - python3-dev
        - python3-setuptools
        - python3-pip
        - python3-gdal
        - libpq-dev
        - libgdal-dev
        - supervisor
    - name: Install frontend packages
      become: true
      apt:
        pkg:
        - apache2
        - libapache2-mod-wsgi
        - libapache2-mod-perl2
    - name: Download NVM install script
      get_url:
        url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh
        dest: /tmp/nvm_install.sh
        mode: '0774'
    - name: Execute NVM install script
      shell: /tmp/nvm_install.sh
    - name: Remove NVM install script
      file: path=/tmp/nvm_install.sh state=absent
    - name: Install pip
      shell: python3 -m pip install pip==20.1.1
    - name: Install virtualenv
      pip:
        name: virtualenv==20.0.23
